version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    init: true
    environment:
      - PG_CONN=postgresql://postgres:mysecretpassword@postgres:5432/postgres
      - REDIS_CONN=redis://redis:6379

  postgres:
    image: "postgres:14"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  redis:
    image: "redis:6"
    ports:
      - 6379:6379
